spring.application.name=Session9

#Config datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/session9_db
spring.datasource.username=postgres
spring.datasource.password=1

#Config jpa
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud-name=dkkd1nhqr
cloudinary.api-key=812182536878189
cloudinary.api-secret=2p2Kchn5hwo3mxqcBB46eyr9OX4

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB